#!/bin/bash

GIT_PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_PROJECT_ROOT"
docker build -f ./pre-commit.Dockerfile -t pre-commit-spf . && docker run --rm --name pre-commit-oidc-auth-lib-run -v $(pwd)/:/sourcecode -v pre-commit-cache:/root/.cache/pre-commit pre-commit-spf
